src/Entity/Cotisation.php
<?php

namespace App\Entity;

use App\Repository\CotisationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: CotisationRepository::class)]
class Cotisation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::BIGINT)]
    private ?int $montant_cotisation = 1000;


    #[ORM\ManyToOne(inversedBy: 'cotisations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Adherent $adherent = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_cotisation = null;

    #[ORM\ManyToOne(inversedBy: 'cotisations')]
    private ?User $user = null;

    #[ORM\Column(nullable: true)]
    #[Gedmo\Timestampable(on: 'create')]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    #[Gedmo\Timestampable(on: 'update')]
    private ?\DateTimeImmutable $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMontantCotisation(): ?string
    {
        return $this->montant_cotisation;
    }

    public function setMontantCotisation(string $montant_cotisation): self
    {
        $this->montant_cotisation = $montant_cotisation;

        return $this;
    }

    public function getAdherent(): ?Adherent
    {
        return $this->adherent;
    }

    public function setAdherent(?Adherent $adherent): self
    {
        $this->adherent = $adherent;

        return $this;
    }

    public function getDateCotisation(): ?\DateTimeInterface
    {
        return $this->date_cotisation;
    }

    public function setDateCotisation(\DateTimeInterface $date_cotisation): self
    {
        $this->date_cotisation = $date_cotisation;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/CotisationType.php
<?php

namespace App\Form;

use App\Entity\Adherent;
use App\Entity\Cotisation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\WeekType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CotisationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_cotisation', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Date de cotisation',

            ])
            ->add('adherent', EntityType::class, [
                'class' => Adherent::class,
                'choice_label' => 'identifiant',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cotisation::class,
        ]);
    }
}

src/Controller/CotisationController.php
<?php

namespace App\Controller;

use App\Entity\Cotisation;
use App\Form\CotisationType;
use App\Repository\CotisationRepository;
use App\Service\CotisationMailService;
use App\Service\CotisationService;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\WebpackEncoreBundle\Asset\EntrypointLookupInterface;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Error\SyntaxError;

#[Route('/admin/cotisation')]
class CotisationController extends AbstractController
{
    #[Route('/', name: 'app_cotisation_index', methods: ['GET'])]
    public function index(CotisationRepository $cotisationRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $cotisation = $cotisationRepository->findAll();
        $pagination = $paginator->paginate(
            $cotisation, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            15 /*limit per page*/
        );

        return $this->render('cotisation/index.html.twig', [
            'cotisations' => $pagination,
        ]);
    }


    /**
     * @throws SyntaxError
     * @throws TransportExceptionInterface
     * @throws RuntimeError
     * @throws LoaderError
     */
    #[Route('/new', name: 'app_cotisation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, CotisationMailService $cotisationMailService): Response
    {
        $cotisation = new Cotisation();
        $form = $this->createForm(CotisationType::class, $cotisation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cotisation->setUser($this->getUser());
            $entityManager->persist($cotisation);
            $entityManager->flush();

            $cotisationMailService->send($cotisation->getAdherent()->getEmail(), $cotisation);

            return $this->redirectToRoute('app_cotisation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('cotisation/new.html.twig', [
            'cotisation' => $cotisation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cotisation_show', methods: ['GET'])]
    public function show(Cotisation $cotisation): Response
    {
        return $this->render('cotisation/show.html.twig', [
            'cotisation' => $cotisation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_cotisation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cotisation $cotisation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CotisationType::class, $cotisation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_cotisation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('cotisation/edit.html.twig', [
            'cotisation' => $cotisation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cotisation_delete', methods: ['POST'])]
    public function delete(Request $request, Cotisation $cotisation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cotisation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($cotisation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_cotisation_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/download/liste/pdf', name: 'app_cotisation_liste_pdf', methods: ['GET'])]
    public function listPdf(CotisationRepository $cotisationRepository, Pdf $pdf): Response
    {
        $cotisations = $cotisationRepository->findAll();

        $html = $this->renderView('cotisation/pdf/liste.html.twig', ['cotisations' => $cotisations]);


        return new Response(
            $pdf->getOutputFromHtml($html, [
                'enable-local-file-access' => true,
                'orientation' => 'landscape',
                'footer-right' => '[page] / [toPage]',
                'footer-left' => 'Caisse de solidarité, liste des cotisations',
                'header-left' => 'Institut Pasteur de Côte d\'Ivoire',
                'header-right' => '[isodate] à [time]',
            ]),
            200,
            [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'inline; filename="liste cotisations.pdf"',
                'encoding' => 'utf-8',
            ]
        );
    }

    #[Route('/download/paiement/{id}/pdf', name: 'app_cotisation_paiement_pdf', methods: ['GET'])]
    public function paiementPdf(CotisationRepository $cotisationRepository, Pdf $pdf, int $id): Response
    {
        $cotisation = $cotisationRepository->find($id);
        $html = $this->renderView('cotisation/pdf/recu.html.twig', ['cotisation' => $cotisation]);


        return new Response(
            $pdf->getOutputFromHtml($html, [
                'enable-local-file-access' => true,
                'orientation' => 'landscape',
                'page-size' => 'A5',
            ]),
            200,
            [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'inline; filename="paiement de cotisations.pdf"',
                'encoding' => 'utf-8',
            ]
        );
    }
}

templates/cotisation/pdf/liste.html.twig
{% extends "pdf/base.pdf.html.twig" %}

{% block title %}Liste des cotisation{% endblock %}


{% block body %}


    <h1 class="text-center text-uppercase title-table">Liste des cotisation</h1>

    <div class="container-fluid">

        <table class="table table-bordered text-center align-middle">
            <thead>
            <tr>
                <th>Identifiant</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Montant</th>
                <th>par</th>
                <th>Pour</th>
                <th>Date de cotisation</th>
                <th>Modifié le</th>
            </tr>
            </thead>
            <tbody>
            {% for cotisation in cotisations %}
                <tr>
                    <td>{{ cotisation.adherent.identifiant }}</td>
                    <td>{{ cotisation.adherent.nom }}</td>
                    <td>{{ cotisation.adherent.prenom }}</td>
                    <td>{{ cotisation.montantCotisation }} FCFA</td>
                    <td>{{ cotisation.user }}</td>
                    <td>{{ cotisation.dateCotisation ? cotisation.dateCotisation|format_date("full", pattern = "MMMM Y", locale = 'fr') : '' }}</td>
                    <td>{{ cotisation.createdAt ? cotisation.createdAt|format_datetime('full', 'short', locale='fr') : '' }}</td>
                    <td>{{ cotisation.updatedAt ? cotisation.updatedAt|format_datetime('full', 'short', locale='fr') : '' }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

{% endblock %}

templates/cotisation/pdf/recu.html.twig
{% extends "pdf/base.pdf.html.twig" %}

{% block title %}Reçu de cotisation{% endblock %}

{% block body %}

    {% set genre = cotisation.adherent.sexe == 'FEMME' ? 'Madame' : 'Monsieur' %}

    <img class="mb-3" src="{{ absolute_url(asset('images/home/logo-1.png')) }}" alt="Logo">
    <h1 class="recu-title text-center text-uppercase fw-bold mb-3">Reçu de cotisation</h1>


    <div class="pasteur-info text-center mt-3 mb-3">

        <p>
            Paiement de la <strong>cotisation</strong> de {{ genre }} {{ cotisation.adherent.nom }}
            {{ cotisation.adherent.prenom }} pour la date de
            <strong>{{ cotisation.dateCotisation|format_date("full", pattern = "MMMM Y", locale = 'fr') }}</strong>
            par <strong>{{ cotisation.user.adherent.nom }} {{ cotisation.user.adherent.prenom }}</strong> le
            {{ cotisation.createdAt|format_datetime('full', 'none', locale='fr') }}.<br/>
            Le montant de la cotisation est de <strong>{{ cotisation.montantCotisation }} FCFA</strong>.
        </p>

        <p>
            Par conséquent, {{ genre }} {{ cotisation.adherent.nom }} {{ cotisation.adherent.prenom }}
            est à jour pour la date de
            {{ cotisation.dateCotisation|format_date("full", pattern = "MMMM Y", locale = 'fr') }}.
        </p>

    </div>


    <div class="text-center">
        <span class="mx-5">Fait le {{ cotisation.createdAt|format_datetime('full', 'none', locale='fr') }}</span>
        <img class="img-fluid mx-5" src="{{ absolute_url(asset('pdf/cotisations/cachet.png')) }}" alt="cachet" height="150" width="150">
    </div>

    <footer class="footer">
        <div class="info info-caisse">

            <p class="">
                <i>Information du prestataire de service</i><br/>
                <strong>Nom et Prénoms</strong> : {{ genre }} {{ cotisation.user.adherent.nom }} {{ cotisation.user.adherent.prenom }}<br/>
                <strong>Site</strong> : {{ cotisation.user.adherent.site }}<br/>
                <strong>Téléphone</strong> : (+225) {{ cotisation.user.adherent.telephone }}<br/>
                <strong>Email</strong> : {{ cotisation.user.adherent.email }}
            </p>

        </div>

        <div class="info info-adherent">

            <p class="">
                <i>Information sur l'adhérent</i><br/>
                <strong>Nom et Prénoms</strong> : {{ cotisation.adherent.nom }} {{ cotisation.adherent.prenom }}<br/>
                <strong>Site</strong> : {{ cotisation.adherent.site }}<br/>
                <strong>Téléphone</strong> : (+225) {{ cotisation.adherent.telephone }}<br/>
                <strong>Email</strong> : {{ cotisation.adherent.email }}
            </p>

        </div>
    </footer>

{% endblock %}