src/Entity/DroitAdhesion.php
<?php

namespace App\Entity;

use App\Repository\DroitAdhesionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


#[ORM\Entity(repositoryClass: DroitAdhesionRepository::class)]
class DroitAdhesion
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::BIGINT)]
    private ?int $montant = 3000;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_adhesion = null;

    #[ORM\ManyToOne(inversedBy: 'droit_adhesion')]
    private ?Adherent $adherent = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMontant(): ?string
    {
        return $this->montant;
    }

    public function setMontant(string $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDateAdhesion(): ?\DateTimeInterface
    {
        return $this->date_adhesion;
    }

    public function setDateAdhesion(\DateTimeInterface $date_adhesion): self
    {
        $this->date_adhesion = $date_adhesion;

        return $this;
    }

    public function getAdherent(): ?Adherent
    {
        return $this->adherent;
    }

    public function setAdherent(?Adherent $adherent): self
    {
        $this->adherent = $adherent;

        return $this;
    }

    public function __toString()
    {
        return $this->montant;
    }
}

src/Form/DroitAdhesionType.php
<?php

namespace App\Form;

use App\Entity\Adherent;
use App\Entity\DroitAdhesion;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DroitAdhesionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_adhesion', DateTimeType::class, [
                'widget' => 'single_text',
            ])
            ->add('adherent', EntityType::class, [
                'class' => Adherent::class,
                'choice_label' => 'identifiant',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => DroitAdhesion::class,
        ]);
    }
}

src/Controller/DroitAdhesionController.php
<?php

namespace App\Controller;

use App\Entity\DroitAdhesion;
use App\Form\DroitAdhesionType;
use App\Repository\DroitAdhesionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/droit/adhesion')]
class DroitAdhesionController extends AbstractController
{
    #[Route('/', name: 'app_droit_adhesion_index', methods: ['GET'])]
    public function index(DroitAdhesionRepository $droitAdhesionRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $adhesion = $droitAdhesionRepository->findAll();
        $pagination = $paginator->paginate(
            $adhesion, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            15 /*limit per page*/
        );

        return $this->render('droit_adhesion/index.html.twig', [
            'droit_adhesions' => $pagination,
        ]);
    }

    #[Route('/new', name: 'app_droit_adhesion_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $droitAdhesion = new DroitAdhesion();
        $form = $this->createForm(DroitAdhesionType::class, $droitAdhesion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($droitAdhesion);
            $entityManager->flush();

            return $this->redirectToRoute('app_droit_adhesion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('droit_adhesion/new.html.twig', [
            'droit_adhesion' => $droitAdhesion,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_droit_adhesion_show', methods: ['GET'])]
    public function show(DroitAdhesion $droitAdhesion): Response
    {
        return $this->render('droit_adhesion/show.html.twig', [
            'droit_adhesion' => $droitAdhesion,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_droit_adhesion_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, DroitAdhesion $droitAdhesion, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DroitAdhesionType::class, $droitAdhesion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_droit_adhesion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('droit_adhesion/edit.html.twig', [
            'droit_adhesion' => $droitAdhesion,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_droit_adhesion_delete', methods: ['POST'])]
    public function delete(Request $request, DroitAdhesion $droitAdhesion, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$droitAdhesion->getId(), $request->request->get('_token'))) {
            $entityManager->remove($droitAdhesion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_droit_adhesion_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/download/pdf', name: 'app_adhesion_liste_pdf', methods: ['GET'])]
    public function downloadPdf(DroitAdhesionRepository $droitAdhesionRepository, Pdf $pdf): Response
    {
        $adhesions = $droitAdhesionRepository->findAll();

        $html = $this->renderView('droit_adhesion/pdf/liste.html.twig', ['adhesions' => $adhesions]);


        return new Response(
            $pdf->getOutputFromHtml($html, [
                'enable-local-file-access' => true,
                'orientation' => 'landscape',
                'footer-right' => '[page] / [toPage]',
                'footer-left' => 'Caisse de solidarité, liste des adhésions',
                'header-left' => 'Institut Pasteur de Côte d\'Ivoire',
                'header-right' => '[isodate] à [time]',

            ]),
            200,
            [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'inline; filename="liste adhesions.pdf"',
                'encoding' => 'utf-8',
            ]
        );
    }
}

templates/droit_adhesion/_delete_form.html.twig
<form method="post" action="{{ path('app_droit_adhesion_delete', {'id': droit_adhesion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ droit_adhesion.id) }}">
    <button class="btn btn-danger">
        <i class="fa fa-trash"></i>
        Supprimer
    </button>
</form>

templates/droit_adhesion/_form.html.twig
{{ form_start(form) }}
    <div class="row">
        <div class="col-4 mb-4">
            {{ form_label(form.adherent, 'Adherent') }}
            {{ form_widget(form.adherent) }}
        </div>

        <div class="col-4 mb-4">
            {{ form_label(form.date_adhesion, 'Date d\'adhésion') }}
            {{ form_widget(form.date_adhesion) }}
        </div>

    </div>

    <button class="btn btn-primary">
        <i class="fa-solid fa-floppy-disk"></i>
        {{ button_label|default('Enregistrer') }}
    </button>
{{ form_end(form) }}

templates/droit_adhesion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit DroitAdhesion{% endblock %}

{% block body %}

    <div class="container">
        <div class="d-flex justify-content-between align-items-center">

            <div class="mb-4">
                <h1>Modifier une adhésion</h1>
            </div>

            <div class="d-flex">
                <a class="btn btn-info me-3" href="{{ path('app_droit_adhesion_index') }}">
                    <i class="fa-solid fa-arrow-left"></i>
                    retour à la liste
                </a>
                {{ include('droit_adhesion/_delete_form.html.twig') }}
            </div>

        </div>

        {{ include('droit_adhesion/_form.html.twig', {'button_label': 'Modifier'}) }}

    </div>
{% endblock %}

templates/droit_adhesion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des adhesions{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="d-flex justify-content-between align-items-center">

            <div class="">
                <h1 class="mb-4">Liste des adhésions</h1>
            </div>

            <div class="d-flex">

                <a class="btn btn-danger me-3" href="{{ path('app_adhesion_liste_pdf') }}" target="_blank">
                    <i class="fa-solid fa-download"></i>
                    Exporter la liste
                </a>

                <a class="btn btn-secondary me-3" href="{{ path('app_adherent_new') }}">
                    <i class="fa-solid fa-filter"></i>
                    Filtre
                </a>

                <a class="btn btn-primary me-3" href="{{ path('app_droit_adhesion_new') }}">
                    <i class="fa-solid fa-plus"></i>
                    Enregistrer une adhésion
                </a>

            </div>

        </div>

        <table class="table table-bordered table-striped text-center align-middle table-responsive table-sm">
            <thead>
            <tr>
                <th>Identifiant</th>
                <th>Nom</th>
                <th>Prénoms</th>
                <th>Email</th>
                <th>Téléphone</th>
                <th>Sexe</th>
                <th>Site</th>
                <th>Statut</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for droit_adhesion in droit_adhesions %}
                <tr>
                    <td>{{ droit_adhesion.adherent }}</td>
                    <td>{{ droit_adhesion.adherent.nom }}</td>
                    <td>{{ droit_adhesion.adherent.prenom }}</td>
                    <td>{{ droit_adhesion.adherent.email }}</td>
                    <td>{{ droit_adhesion.adherent.telephone }}</td>
                    <td>{{ droit_adhesion.adherent.sexe }}</td>
                    <td>{{ droit_adhesion.adherent.site }}</td>
                    <td>{{ droit_adhesion.adherent.statut }}</td>
                    <td>
                        <a class="btn btn-secondary me-2" href="{{ path('app_droit_adhesion_show', {'id': droit_adhesion.id}) }}">
                            <i class="fa-solid fa-eye"></i>
                            voir plus
                        </a>
                        <a class="btn btn-warning" href="{{ path('app_droit_adhesion_edit', {'id': droit_adhesion.id}) }}">
                            <i class="fa-solid fa-edit"></i>
                            modifier
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {# display navigation #}
        <div class="pagination">
            {{ knp_pagination_render(droit_adhesions) }}
        </div>

    </div>
{% endblock %}

templates/droit_adhesion/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle adhésion{% endblock %}

{% block body %}
    <div class="container">

        <div class="d-flex justify-content-between align-items-center">

            <div class="">
                <h1 class="mb-4">Nouvelle adhésion</h1>
            </div>

            <div class="d-flex">
                <a class="btn btn-info me-3" href="{{ path('app_droit_adhesion_index') }}">
                    <i class="fas fa-arrow-left"></i>
                    retour à la liste
                </a>
            </div>

        </div>

        {{ include('droit_adhesion/_form.html.twig') }}

    </div>
{% endblock %}

templates/droit_adhesion/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adherent{% endblock %}

{% block body %}
    <div class="container">

        <div class="d-flex justify-content-between align-items-center">

            <div class="">
                <h1 class="mb-4">Droit Adhesion</h1>
            </div>

            <div class="d-flex">
                <a class="btn btn-info me-3" href="{{ path('app_droit_adhesion_index') }}">
                    <i class="fa-solid fa-rotate-left"></i>
                    back to list
                </a>
                <a class="btn btn-warning me-3" href="{{ path('app_droit_adhesion_edit', {'id': droit_adhesion.id}) }}">
                    <i class="fa-solid fa-edit"></i>
                    edit
                </a>
                {{ include('droit_adhesion/_delete_form.html.twig') }}
            </div>

        </div>

        <div class="">
            <table class="table table-striped table-bordered">
                <tbody>
                <tr>
                    <th>Adherent</th>
                    <td>{{ droit_adhesion.adherent }}</td>
                </tr>
                <tr>
                    <th>Montant</th>
                    <td>{{ droit_adhesion.montant }}</td>
                </tr>
                <tr>
                    <th>Date_inscription</th>
                    <td>{{ droit_adhesion.dateAdhesion ? droit_adhesion.dateAdhesion|date('Y-m-d') : '' }}</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="row">
            <div class="col-md-6"></div>
            <div class="col-md-6"></div>
        </div>

    </div>
{% endblock %}