src/Entity/Assistance.php
<?php

namespace App\Entity;

use App\Repository\AssistanceRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: AssistanceRepository::class)]
class Assistance
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    #[Gedmo\Timestampable(on: 'create')]
    private ?\DateTimeImmutable $date_assistance = null;

    #[ORM\ManyToOne(inversedBy: 'assistance')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Adherent $adherent = null;

    #[ORM\ManyToOne(inversedBy: 'assistances')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Evenement $evenement = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateAssistance(): ?\DateTimeImmutable
    {
        return $this->date_assistance;
    }

    public function setDateAssistance(\DateTimeImmutable $date_assistance): self
    {
        $this->date_assistance = $date_assistance;

        return $this;
    }

    public function getAdherent(): ?Adherent
    {
        return $this->adherent;
    }

    public function setAdherent(?Adherent $adherent): self
    {
        $this->adherent = $adherent;

        return $this;
    }

    public function getEvenement(): ?Evenement
    {
        return $this->evenement;
    }

    public function setEvenement(?Evenement $evenement): self
    {
        $this->evenement = $evenement;

        return $this;
    }

}

src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EvenementRepository::class)]
class Evenement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\Column(type: Types::BIGINT)]
    private ?string $montant_event = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?TypeAssistance $type_assistance = null;

    #[ORM\OneToMany(mappedBy: 'evenement', targetEntity: Assistance::class)]
    private Collection $assistances;

    public function __construct()
    {
        $this->assistances = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getMontantEvent(): ?string
    {
        return $this->montant_event;
    }

    public function setMontantEvent(string $montant_event): self
    {
        $this->montant_event = $montant_event;

        return $this;
    }

    public function getTypeAssistance(): ?TypeAssistance
    {
        return $this->type_assistance;
    }

    public function setTypeAssistance(?TypeAssistance $type_assistance): self
    {
        $this->type_assistance = $type_assistance;

        return $this;
    }

    /**
     * @return Collection<int, Assistance>
     */
    public function getAssistances(): Collection
    {
        return $this->assistances;
    }

    public function addAssistance(Assistance $assistance): self
    {
        if (!$this->assistances->contains($assistance)) {
            $this->assistances->add($assistance);
            $assistance->setEvenement($this);
        }

        return $this;
    }

    public function removeAssistance(Assistance $assistance): self
    {
        if ($this->assistances->removeElement($assistance)) {
            // set the owning side to null (unless already changed)
            if ($assistance->getEvenement() === $this) {
                $assistance->setEvenement(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->libelle;
    }
}

src/Form/AssistanceType.php
<?php

namespace App\Form;

use App\Entity\Adherent;
use App\Entity\Assistance;
use App\Entity\Evenement;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AssistanceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('adherent', EntityType::class, [
                'class' => Adherent::class,
                'choice_label' => 'identifiant',
            ])
            ->add('evenement', EntityType::class, [
                'class' => Evenement::class,
                'choice_label' => 'libelle',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Assistance::class,
        ]);
    }
}

src/Controller/AssistanceController.php
<?php

namespace App\Controller;

use App\Entity\Assistance;
use App\Form\AssistanceType;
use App\Repository\AssistanceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/assistance')]
class AssistanceController extends AbstractController
{
    #[Route('/', name: 'app_assistance_index', methods: ['GET'])]
    public function index(AssistanceRepository $assistanceRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $assistances = $assistanceRepository->findAll();
        $pagination = $paginator->paginate(
            $assistances,
            $request->query->getInt('page', 1),
            15
        );

        return $this->render('assistance/index.html.twig', [
            'assistances' => $pagination,
        ]);
    }

    #[Route('/new', name: 'app_assistance_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $assistance = new Assistance();
        $form = $this->createForm(AssistanceType::class, $assistance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($assistance);
            $entityManager->flush();

            return $this->redirectToRoute('app_assistance_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('assistance/new.html.twig', [
            'assistance' => $assistance,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_assistance_show', methods: ['GET'])]
    public function show(Assistance $assistance): Response
    {
        return $this->render('assistance/show.html.twig', [
            'assistance' => $assistance,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_assistance_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Assistance $assistance, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AssistanceType::class, $assistance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_assistance_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('assistance/edit.html.twig', [
            'assistance' => $assistance,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_assistance_delete', methods: ['POST'])]
    public function delete(Request $request, Assistance $assistance, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$assistance->getId(), $request->request->get('_token'))) {
            $entityManager->remove($assistance);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_assistance_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/download/pdf', name: 'app_assistance_liste_pdf', methods: ['GET'])]
    public function downloadPdf(AssistanceRepository $assistanceRepository, Pdf $pdf): Response
    {
        $assistances = $assistanceRepository->findAll();

        $html = $this->renderView('assistance/pdf/liste.html.twig', ['assistances' => $assistances]);


        return new Response(
            $pdf->getOutputFromHtml($html, [
                'enable-local-file-access' => true,
                'orientation' => 'landscape',
                'footer-right' => '[page] / [toPage]',
                'footer-left' => 'Caisse de solidarité, liste des assistances',
                'header-left' => 'Institut Pasteur de Côte d\'Ivoire',
                'header-right' => '[isodate] à [time]',
            ]),
            200,
            [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'inline; filename="liste assistance.pdf"',
                'encoding' => 'utf-8',
            ]
        );
    }
}

templates/assistance/_delete_form.html.twig
<form method="post" action="{{ path('app_assistance_delete', {'id': assistance.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ assistance.id) }}">
    <button class="btn btn-danger">
        <i class="fa-solid fa-trash"></i>
        Supprimer
    </button>
</form>

templates/assistance/_form.html.twig
{{ form_start(form) }}

    <div class="row">
        <div class="col-6 mb-4">
            {{ form_label(form.adherent, 'Adhérent') }}
            {{ form_widget(form.adherent) }}
        </div>
        <div class="col-6 mb-4">
            {{ form_label(form.evenement, 'Evenement') }}
            {{ form_widget(form.evenement) }}
        </div>
    </div>

    <button class="btn btn-primary">
        <i class="fas fa-save"></i>
        {{ button_label|default('Enregistrer') }}
    </button>

{{ form_end(form) }}

templates/assistance/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Assistance{% endblock %}

{% block body %}

    <div class="container">
        <div class="d-flex justify-content-between align-items-center">

            <div class="">
                <h1 class="mb-4">Modifier une assistance</h1>
            </div>

            <div class="d-flex">
                <a class="btn btn-info mx-4" href="{{ path('app_assistance_index') }}">
                    <i class="fa-solid fa-arrow-left"></i>
                    retour à la liste
                </a>
                {{ include('assistance/_delete_form.html.twig') }}
            </div>

        </div>

        {{ include('assistance/_form.html.twig', {'button_label': 'Modifier'}) }}

    </div>

{% endblock %}

templates/assistance/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des assistances{% endblock %}

{% block body %}

    <div class="container-fluid">

        <div class="d-flex justify-content-between align-items-center table-responsive table-sm">

            <div class="">
                <h1 class="mb-4">Liste des assistances</h1>
            </div>

            <div class="d-flex">

                <a class="btn btn-danger me-3" href="{{ path('app_assistance_liste_pdf') }}" target="_blank">
                    <i class="fa-solid fa-download"></i>
                    Exporter la liste
                </a>

                <a class="btn btn-secondary me-3" href="{{ path('app_assistance_index') }}">
                    <i class="fa-solid fa-filter"></i>
                    Filtre
                </a>

                <a class="btn btn-primary me-3" href="{{ path('app_assistance_new') }}">
                    <i class="fa-solid fa-plus"></i>
                    Assister un adhérent
                </a>

            </div>

        </div>

        <table class="table table-bordered table-striped text-center table-responsive table-sm align-middle">
            <thead>
            <tr>
                <th>Identifiant</th>
                <th>Nom</th>
                <th>Prénoms</th>
                <th>Email</th>
                <th>Téléphone</th>
                <th>Évènement</th>
                <th>Assisté le</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for assistance in assistances %}
                <tr>
                    <td>{{ assistance.adherent}}</td>
                    <td>{{ assistance.adherent.nom }}</td>
                    <td>{{ assistance.adherent.prenom }}</td>
                    <td>{{ assistance.adherent.email }}</td>
                    <td>{{ assistance.adherent.telephone }}</td>
                    <td>{{ assistance.evenement }}</td>
                    <td>{{ assistance.dateAssistance|format_datetime('full', 'short', locale='fr') }}</td>
                    <td>
                        <a class="btn btn-secondary me-2" href="{{ path('app_assistance_show', {'id': assistance.id}) }}">
                            <i class="fa-solid fa-eye"></i>
                            Voir plus
                        </a>
                        <a class="btn btn-warning" href="{{ path('app_assistance_edit', {'id': assistance.id}) }}">
                            <i class="fa-solid fa-edit"></i>
                            Modifier
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="pagination">
            {{ knp_pagination_render(assistances) }}
        </div>

    </div>

{% endblock %}

templates/assistance/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle assistance{% endblock %}

{% block body %}

    <div class="container">

        <div class="d-flex justify-content-between align-items-center">

            <div class="">
                <h1 class="mb-4">Assister un adhérent</h1>
            </div>

            <div class="d-flex">
                <a class="btn btn-info me-3" href="{{ path('app_assistance_index') }}">
                    <i class="fas fa-arrow-left"></i>
                    retour à la liste
                </a>
            </div>

        </div>

        {{ include('assistance/_form.html.twig') }}

    </div>


{% endblock %}

templates/assistance/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Détail d'une assistance
{% endblock %}

{% block body %}

    {% set genre = assistance.adherent.sexe == 'FEMME' ? 'Madame' : 'Monsieur' %}

    <div class="container">

        {# Logo et Boutons #}
        <div class="d-flex justify-content-between align-items-center mb-4">

            <div class="logo">
                <img class="mb-3" src="{{ absolute_url(asset('images/home/logo-1.png')) }}" alt="Logo">
            </div>

            <div class="d-flex">
                <a class="btn btn-info me-3" href="{{ path('app_assistance_index') }}">
                    <i class="fa-solid fa-rotate-left"></i>
                    retour à la liste
                </a>
                <a class="btn btn-warning me-3" href="{{ path('app_assistance_edit', {'id': assistance.id}) }}">
                    <i class="fa-solid fa-edit"></i>
                    modifier
                </a>
                {{ include('assistance/_delete_form.html.twig') }}
            </div>

        </div>

        {# Titre #}
        <h1 class="recu-title text-center text-uppercase fw-bold mb-3">
            Détail d'une assistance
        </h1>

        {# Message sur la cotisation #}
        <div class="text-center mt-3 mb-3">

            <p>
                Le <strong>{{ assistance.dateAssistance|format_date("full", pattern = "MMMM Y", locale = 'fr') }} </strong> {{ genre }}
                <strong>{{ assistance.adherent.nom }} {{ assistance.adherent.prenom }}</strong> a été assisté par la caisse de solidarité
                de l'Institut Pasteur de Côte d'Ivoire pour le motif de <strong>({{ assistance.evenement }})</strong>.
                L'assistance a été enregistrée par <strong>aaaaaaa bbbbbbbbbb</strong> le
                <strong>2023-11-31</strong>.
            </p>

            <p>
                Le montant de l'assistance est évalué à <strong>{{ assistance.evenement.montantEvent }} FCFA</strong>.
            </p>

        </div>

        {# Date et Cachet #}
        <div class="text-center mb-4">
            <span class="mx-5">Fait le {{ assistance.dateAssistance|format_datetime('full', 'none', locale='fr') }}</span>
            <img class="img-fluid mx-5" src="{{ absolute_url(asset('pdf/cotisations/cachet.png')) }}" alt="cachet" height="150" width="150">
        </div>

        {# Information caisse et adhérent #}
        <div class="d-flex justify-content-around">

            <div class="">

                <p class="">
                    <i>Information du prestataire de service</i><br/>
                    <strong>Nom et Prénoms</strong> : Madame aaaaaa bbbbbbb<br/>
                    <strong>Site</strong> : Adiopodoumé<br/>
                    <strong>Téléphone</strong> : (+225) 0102030405<br/>
                    <strong>Email</strong> : test@mail.com
                </p>

            </div>

            <div class="">

                <p class="">
                    <i>Information sur l'adhérent</i><br/>
                    <strong>Nom et Prénoms</strong> : {{ assistance.adherent.nom }} {{ assistance.adherent.prenom }}<br/>
                    <strong>Site</strong> : {{ assistance.adherent.site }}<br/>
                    <strong>Téléphone</strong> : (+225) {{ assistance.adherent.telephone }}<br/>
                    <strong>Email</strong> : {{ assistance.adherent.email }}
                </p>

            </div>

        </div>

        {# Bouton exporter en pdf #}
{#        <div class="text-center mt-5">#}
{#            <a class="btn btn-success" href="{{ path('app_cotisation_paiement_pdf', {'id': cotisation.id}) }}" target="_blank">#}
{#                <i class="fa-solid fa-file-pdf"></i>#}
{#                Exporter en PDF#}
{#            </a>#}
{#        </div>#}

    </div>

{% endblock %}